# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20190325_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
